// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grad.Data;

#nullable disable

namespace grad.Migrations
{
    [DbContext(typeof(Db_Context))]
    [Migration("20260123211053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grad.Model.EnrolledStudent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("STUFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SUBFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("STUFK", "SUBFK");

                    b.HasIndex("SUBFK");

                    b.ToTable("EnrolledSubjects");
                });

            modelBuilder.Entity("grad.Model.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("grad.Model.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("deaf_mute")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("grad.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailorUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("gender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("grad.Model.Admin", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<string>("AdminType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reletationShip")
                        .HasColumnType("int");

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Disability")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasIndex("PID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("grad.Model.Teacher", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("SubjectFK");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("grad.Model.EnrolledStudent", b =>
                {
                    b.HasOne("grad.Model.Student", "Student")
                        .WithMany("EnrolledSubjects")
                        .HasForeignKey("STUFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Subject", "subject")
                        .WithMany("Students")
                        .HasForeignKey("SUBFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("grad.Model.RefreshToken", b =>
                {
                    b.HasOne("grad.Model.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("grad.Model.RefreshToken", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("grad.Model.Admin", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Parent", "parent")
                        .WithMany("students")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("parent");
                });

            modelBuilder.Entity("grad.Model.Teacher", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectFK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("grad.Model.Subject", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("grad.Model.User", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.Navigation("EnrolledSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
