// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grad.Data;

#nullable disable

namespace grad.Migrations
{
    [DbContext(typeof(Db_Context))]
    [Migration("20260221122713_v6")]
    partial class v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grad.Model.AssignedSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Assigned_At")
                        .HasColumnType("date");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssignedSubjects");
                });

            modelBuilder.Entity("grad.Model.Enrollement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Enrolled_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("STUFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SUBFK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("STUFK", "SUBFK");

                    b.HasIndex("SUBFK");

                    b.ToTable("Enrollents");
                });

            modelBuilder.Entity("grad.Model.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("grad.Model.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("deaf_mute")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("grad.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailorUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("gender")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("grad.Model.Admin", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<string>("AdminType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("reletationShip")
                        .HasColumnType("int");

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Disability")
                        .HasColumnType("int");

                    b.Property<Guid?>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasIndex("PID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("grad.Model.Teacher", b =>
                {
                    b.HasBaseType("grad.Model.User");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasIndex("SubjectId");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("grad.Model.AssignedSubject", b =>
                {
                    b.HasOne("grad.Model.Subject", "Subject")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Teacher", "Teacher")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("grad.Model.Enrollement", b =>
                {
                    b.HasOne("grad.Model.Student", "Student")
                        .WithMany("EnrolledSubjects")
                        .HasForeignKey("STUFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Subject", "subject")
                        .WithMany("Students")
                        .HasForeignKey("SUBFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("grad.Model.RefreshToken", b =>
                {
                    b.HasOne("grad.Model.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("grad.Model.RefreshToken", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("grad.Model.Admin", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Parent", "parent")
                        .WithMany("students")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("grad.Model.Teacher", b =>
                {
                    b.HasOne("grad.Model.User", null)
                        .WithOne()
                        .HasForeignKey("grad.Model.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grad.Model.Subject", null)
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("grad.Model.Subject", b =>
                {
                    b.Navigation("AssignedSubjects");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("grad.Model.User", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();
                });

            modelBuilder.Entity("grad.Model.Parent", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("grad.Model.Student", b =>
                {
                    b.Navigation("EnrolledSubjects");
                });

            modelBuilder.Entity("grad.Model.Teacher", b =>
                {
                    b.Navigation("AssignedSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
